[package]
name = "oidc-dev-rust"
version = "0.1.0"
authors = ["Nephtys <christopher.kaag@gmail.com>"]

[dependencies]
time = "0.1"
router = "*"
rustc-serialize = "0.3"
params = "*"

[dependencies.iron]
version = "*"
features = ["ssl"]
